# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labman_setup', '0005_auto_20150915_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmandeploygeneralsettings',
            name='base_url',
            field=models.URLField(default='http://morelab.deusto.es'),
            preserve_default=False,
        ),
    ]
