# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:21
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_private_participant_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=redactor.fields.RedactorField(blank=True, max_length=7500, null=True),
        ),
    ]
