# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20150930_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='viva_outcome',
            field=models.CharField(blank=True, choices=[(b'Apt', b'Apt'), (b'Cum Laude', b'Cum Laude'), (b'Cum Laude by unanimity', b'Cum Laude by unanimity'), (b'Pass with distinction', b'Pass with distinction'), (b'Pass with distinction by unanimity', b'Pass with distinction by unanimity')], default=b'Apt', max_length=250),
        ),
    ]
